import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, '..', '..');

const TARGETS = [
  { file: 'src/ubg/apocalypse.js', test: 'tests/verdict-partial.test.js' },
  { file: 'src/ubg/nestjs.js', test: 'tests/nest-custom-resolver.test.js' },
  { file: 'src/ubg/extract.js', test: 'tests/guard-dominance.test.js' },
];

const OLLAMA_URL = 'http://localhost:11434/api/generate';
const MODEL = 'qwen2.5-coder:1.5b';
const MAX_MUTANTS = 15000;
const REPORT_FILE = path.join(HERE, 'bilan-fuzzing-ia.json');

// Ensure report file exists
if (!fs.existsSync(REPORT_FILE)) {
  fs.writeFileSync(
    REPORT_FILE,
    JSON.stringify({ KILLED: 0, SURVIVED: 0, mutants: [] }, null, 2),
  );
}

async function generateMutation(targetContent) {
  const prompt = `
You are an expert security researcher testing a static analysis engine.
I will give you a piece of JS source code.
Your goal is to mutate the code slightly (e.g. change a boolean, alter a condition, remove a return, change an array mapping).
The mutation MUST introduce a silent vulnerability, logic flaw, or make the engine miss something.
The syntax MUST remain perfectly valid Javascript.
Output ONLY a raw JSON object with the exact string to find and the replacement. No markdown, no comments.
Format: {"search": "exact line to replace", "replace": "the malicious replacement"}

Code snippet:
${targetContent.slice(0, 3000)} // Using a snippet to keep context fast
`;

  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 10000); // 10s timeout for AI

    const res = await fetch(OLLAMA_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      signal: controller.signal,
      body: JSON.stringify({
        model: MODEL,
        prompt: prompt,
        stream: false,
        format: 'json',
      }),
    });

    clearTimeout(timeoutId);

    const data = await res.json();
    return JSON.parse(data.response);
  } catch (err) {
    console.error(
      'Ollama API error or JSON parse error (retrying next loop):',
      err.message,
    );
    return null;
  }
}

async function runFuzzer() {
  console.log(
    `Starting AI Fuzzing Campaign against Sparda (${MAX_MUTANTS} mutations)...`,
  );

  const report = JSON.parse(fs.readFileSync(REPORT_FILE, 'utf8'));

  for (let i = 1; i <= MAX_MUTANTS; i++) {
    const target = TARGETS[Math.floor(Math.random() * TARGETS.length)];
    const absPath = path.join(REPO, target.file);
    const origCode = fs.readFileSync(absPath, 'utf8');

    console.log(
      `\n[Mutation ${i}/${MAX_MUTANTS}] Requesting mutation for ${target.file} from ${MODEL}...`,
    );
    const mutation = await generateMutation(origCode);

    if (!mutation || !mutation.search || !mutation.replace) {
      console.log('Skipping: Invalid AI output.');
      continue;
    }

    if (!origCode.includes(mutation.search)) {
      console.log(
        'Skipping: The search string generated by AI was not found in the source file.',
      );
      continue;
    }

    // Apply mutation
    const mutatedCode = origCode.replace(mutation.search, mutation.replace);
    fs.writeFileSync(absPath, mutatedCode);

    // WHY the test failed decides what the run measured. A non-zero exit has three very
    // different causes, and collapsing them into "KILLED" is how a fuzzer reports 100 % without
    // having earned any of it:
    //
    //   PARSE   — the mutant was not valid JavaScript, so Babel refused the file. EVERY test
    //             would fail; this measures the parser, not the suite. Not a kill.
    //   TIMEOUT — the run was killed before it finished. We did not measure anything, and
    //             calling that a kill is the exact inversion SPARDA exists to forbid. Worse:
    //             a mutation that makes the analyser hang WOULD land here and read as "caught".
    //   KILLED  — the test ran to completion and its assertions failed. This is the real thing.
    //
    // Baseline for the three target tests is 1.1–1.6 s, so 15 s leaves an order of magnitude of
    // headroom: a timeout now means something pathological, and it is reported as unmeasured.
    let outcome = 'SURVIVED';
    let detail = '';
    try {
      execFileSync('npx', ['vitest', 'run', target.test], {
        cwd: REPO,
        stdio: 'pipe',
        timeout: 15000,
      });
    } catch (e) {
      const errOutput = `${e.stdout?.toString() ?? ''}${e.stderr?.toString() ?? ''}`;
      detail = errOutput.trim().split('\n').slice(-3).join(' | ');
      if (e.signal === 'SIGTERM' || e.code === 'ETIMEDOUT') outcome = 'TIMEOUT';
      else if (
        /SyntaxError|Transform failed|Unexpected token|Failed to parse/i.test(errOutput)
      )
        outcome = 'PARSE_ERROR';
      else outcome = 'KILLED';
    } finally {
      // ALWAYS restore
      fs.writeFileSync(absPath, origCode);
    }
    console.log(`Mutation Outcome: ${outcome}`);

    // EVERY mutant is recorded, not only the survivors. A campaign that keeps nothing but a
    // count cannot be audited afterwards — and "2224 killed, 0 survived" with no record of what
    // was mutated is a number nobody, including us, can reproduce or check.
    report[outcome] = (report[outcome] ?? 0) + 1;
    report.mutants.push({
      file: target.file,
      test: target.test,
      search: mutation.search,
      replace: mutation.replace,
      status: outcome,
      ...(detail ? { detail } : {}),
    });

    // Save every 10 iterations to avoid losing data on crash
    if (i % 10 === 0) {
      fs.writeFileSync(REPORT_FILE, JSON.stringify(report, null, 2));
    }
  }

  // Final Save
  fs.writeFileSync(REPORT_FILE, JSON.stringify(report, null, 2));

  // The denominator that means something is the INJECTED-AND-RAN one. A mutant the parser
  // refused, or one whose run was cut short, tells us nothing about the suite — reporting it as
  // a kill inflates the score with exactly the measurements we failed to take.
  const killed = report.KILLED ?? 0;
  const survived = report.SURVIVED ?? 0;
  const parse = report.PARSE_ERROR ?? 0;
  const timeout = report.TIMEOUT ?? 0;
  const scored = killed + survived;
  console.log(`\n=== FUZZING COMPLETE ===`);
  console.log(`Injected:            ${scored + parse + timeout}`);
  console.log(`  killed by tests:   ${killed}`);
  console.log(`  SURVIVED (holes):  ${survived}`);
  console.log(`  parse errors:      ${parse}   ← rejected by Babel, measures nothing`);
  console.log(`  timed out:         ${timeout}   ← UNMEASURED, never counted as caught`);
  console.log(
    `Kill rate over mutants that actually ran: ${scored ? ((killed / scored) * 100).toFixed(1) : '—'}%  (${killed}/${scored})`,
  );
  console.log(`Full report saved to ${REPORT_FILE}`);
}

runFuzzer().catch(console.error);
