export type Lang = 'fr' | 'en';

export const copy = {
  fr: {
    intro: [
      { text: `L'IA ÉCRIT`, accent: false, invert: false },
      { text: `DU CODE`, accent: false, invert: false },
      { text: `EN 3 SECONDES.`, accent: true, invert: false },
      { text: `QUI LE VÉRIFIE ?`, accent: false, invert: false },
      { text: `PERSONNE.`, accent: false, invert: true },
    ],
    hook1: `L'IA écrit`,
    hook2: `ton backend.`,
    hookSub: `Vite. Très vite.`,
    editCaption: `Elle vient de supprimer\nta garde d'authentification.`,
    gateTitle: `BLOQUÉ`,
    gateSub: `garde supprimée · route exposée`,
    gateCaption: `SPARDA le bloque.\nÀ la seconde. Hors-ligne.`,
    proveCaption: `Puis il prouve le reste.`,
    provenChip: `PROVEN`,
    provenMeta: `coverage 96% · 579 routes · 1.2s`,
    outroSign1: `AI writes. SPARDA proves.`,
    outroSign2: `L'IA écrit. SPARDA prouve.`,
    outroBaseline: `RUNTIME AU COMPORTEMENT DÉTERMINISTE`,
    cmd: `npx sparda-mcp prove`,
  },
  en: {
    intro: [
      { text: `AI WRITES`, accent: false, invert: false },
      { text: `CODE`, accent: false, invert: false },
      { text: `IN 3 SECONDS.`, accent: true, invert: false },
      { text: `WHO CHECKS IT?`, accent: false, invert: false },
      { text: `NOBODY.`, accent: false, invert: true },
    ],
    hook1: `AI writes`,
    hook2: `your backend.`,
    hookSub: `Fast. Very fast.`,
    editCaption: `It just removed\nyour auth guard.`,
    gateTitle: `BLOCKED`,
    gateSub: `guard removed · route exposed`,
    gateCaption: `SPARDA blocks it.\nInstantly. Offline.`,
    proveCaption: `Then it proves the rest.`,
    provenChip: `PROVEN`,
    provenMeta: `coverage 96% · 579 routes · 1.2s`,
    outroSign1: `AI writes. SPARDA proves.`,
    outroSign2: `L'IA écrit. SPARDA prouve.`,
    outroBaseline: `DETERMINISTIC BEHAVIOR RUNTIME`,
    cmd: `npx sparda-mcp prove`,
  },
} as const;
