// commands/timeless.js — production bugs become unit tests.
//   sparda timeless                 list recorded flights
//   sparda timeless replay <id>     re-fly the request against current code
//   sparda timeless export <id>     generate a vitest test that replays it
// Recording side: mount the recorder in the app (2 lines, documented in the
// README) — `const flight = createFlightBox(); app.use(flight.middleware())`.
// Replay imports the real entry file with `listen()` suppressed, feeds every
// recorded tap back in strict order, and compares the response byte-for-byte.
import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import { pathToFileURL } from 'node:url';
import { detectStack } from '../detect.js';
import { getFlightBox } from '../flight/box.js';
import { replayFlight } from '../flight/replayer.js';
import { listFlights, loadFlight } from '../flight/format.js';
import { atomicWriteFileSync as atomicWrite } from '../server/persistence.js';

const err = (message, hint) => Object.assign(new Error(message), { code: 'USER', hint });

export async function runTimeless(opts, args) {
  const [sub, id] = args.filter((a) => !a.startsWith('--'));

  if (!sub || sub === 'list') return list(opts);
  if (sub === 'replay') return replay(opts, requireId(id));
  if (sub === 'export') return exportTest(opts, requireId(id));
  throw err(
    `unknown timeless subcommand "${sub}"`,
    'use: list | replay <id> | export <id>',
  );
}

const requireId = (id) => {
  if (!id) throw err('flight id required', 'run `sparda timeless` to list flights');
  return id;
};

function list(opts) {
  const flights = listFlights(opts.cwd);
  if (!flights.length) {
    console.log(
      'No flights recorded. Mount the recorder in your app (ESM):\n' +
        "  import { getFlightBox } from 'sparda-mcp/src/flight/box.js';\n" +
        '  const box = getFlightBox(); box.arm();\n' +
        '  app.use(box.middleware());\n' +
        '  const db = box.wrapClient(rawDb); // your query client\n' +
        "  (CJS: const { getFlightBox } = await import('sparda-mcp/src/flight/box.js'))",
    );
    return { flights };
  }
  console.log(`${flights.length} flight(s) in .sparda/flight/`);
  for (const f of flights) {
    const { request, response } = loadFlight(opts.cwd, f);
    console.log(
      `  ${f}  ${request.method} ${request.url} → ${response.status} (${response.body.length}b, ${loadFlight(opts.cwd, f).taps.length} taps)`,
    );
  }
  return { flights };
}

async function replay(opts, id) {
  const flight = loadFlight(opts.cwd, id);
  // the SHARED box: if the app integrates the recorder, its wrapClient rides
  // the same AsyncLocalStorage this replay store lands on — load it BEFORE
  // the app so both resolve the singleton
  const box = getFlightBox();
  const app = await loadApp(opts.cwd);
  box.arm();
  let result;
  try {
    result = await replayFlight(app, flight, box);
  } finally {
    box.disarm();
  }

  console.log(
    `TIMELESS — replaying ${flight.request.method} ${flight.request.url} (${flight.taps.length} taps virtualized)`,
  );
  if (result.match) {
    console.log(
      `✓ byte-identical replay — status ${result.actual.status}, every tap consumed, zero divergence`,
    );
  } else {
    if (!result.statusMatch)
      console.log(
        `  ✗ status: expected ${result.expected.status}, got ${result.actual.status}`,
      );
    if (!result.bodyMatch)
      console.log(
        `  ✗ body differs\n    expected: ${result.expected.body.slice(0, 200)}\n    actual:   ${result.actual.body.slice(0, 200)}`,
      );
    for (const d of result.divergences)
      console.log(
        `  ✗ divergence: expected ${d.kind} "${d.expected}", code asked "${d.got}"`,
      );
    for (const l of result.leftover)
      console.log(
        `  ✗ ${l.unconsumed} unconsumed ${l.kind} tap(s) — the code skipped step(s)`,
      );
    console.log(
      '✗ NOT identical — the code no longer does what it did during the flight',
    );
    process.exitCode = 1;
  }
  return { result };
}

async function exportTest(opts, id) {
  const flight = loadFlight(opts.cwd, id);
  const stack = detectStack(opts.cwd);
  if (stack.framework !== 'express')
    throw err(
      'timeless export supports Express apps in v1',
      'FastAPI replay is a later round',
    );

  const testDir = path.join(opts.cwd, 'tests');
  fs.mkdirSync(testDir, { recursive: true });
  const testFile = path.join(testDir, `flight-${id}.test.js`);
  const relEntry = path
    .relative(testDir, path.resolve(opts.cwd, stack.entryFile))
    .split(path.sep)
    .join('/');

  atomicWrite(
    testFile,
    `// flight-${id}.test.js — generated by \`sparda timeless export ${id}\`
// Replays a recorded production request against the current code. A failure
// means the behavior changed: if the change is the intended fix, re-record
// the flight and re-export — this file asserts the PAST, on purpose.
import { describe, it, expect } from 'vitest';
import { getFlightBox } from 'sparda-mcp/src/flight/box.js';
import { replayFlight } from 'sparda-mcp/src/flight/replayer.js';
import { loadFlight } from 'sparda-mcp/src/flight/format.js';
import appModule from '${relEntry.startsWith('.') ? relEntry : './' + relEntry}';

describe('flight ${id} — ${flight.request.method} ${flight.request.url}', () => {
  it('replays byte-identically', async () => {
    const app = appModule.default ?? appModule;
    const flight = loadFlight(process.cwd(), '${id}');
    // the SHARED box — the app's own wrapClient must see the replay store
    const box = getFlightBox();
    box.arm();
    try {
      const result = await replayFlight(app, flight, box);
      expect(result.divergences).toEqual([]);
      expect(result.actual.status).toBe(result.expected.status);
      expect(result.bodyMatch).toBe(true);
      expect(result.leftover).toEqual([]);
    } finally {
      box.disarm();
    }
  });
});
`,
  );
  console.log(`✓ Test written: tests/flight-${id}.test.js — the bug is now a unit test`);
  return { testFile };
}

// import the real entry with listen() suppressed — replay never binds ports
async function loadApp(cwd) {
  const stack = detectStack(cwd);
  if (stack.framework !== 'express')
    throw err(
      'timeless replay supports Express apps in v1',
      'FastAPI replay is a later round',
    );
  const origListen = http.Server.prototype.listen;
  http.Server.prototype.listen = function suppressedListen(...args) {
    const cb = args.find((a) => typeof a === 'function');
    if (cb) setImmediate(cb);
    return this;
  };
  try {
    const mod = await import(pathToFileURL(path.resolve(cwd, stack.entryFile)).href);
    const app = mod.default ?? mod;
    if (typeof app !== 'function')
      throw err(
        'the entry file does not export the Express app',
        'add `module.exports = app` (CJS) or `export default app` (ESM) to your entry',
      );
    return app;
  } finally {
    http.Server.prototype.listen = origListen;
  }
}
